[env:g474ceu6_stlink]
platform = ststm32
framework = stm32cube
board = nucleo_g474re

board_build.mcu = stm32g474ceu6
board_build.f_cpu = 170000000L
board_build.ldscript = STM32G474CETX_FLASH.ld

#upload_protocol = stlink
#debug_tool = stlink

upload_protocol = blackmagic
debug_tool = blackmagic
debug_port = COM9

monitor_speed = 2000000

build_flags =
    -Wl,-u,_printf_float
    -DHSE_VALUE=8000000