[platformio]
default_envs = esp32_8048S043C
boards_dir = boards

[env:esp32_8048S043C]
platform = espressif32
board = esp32-8048S043C
framework = arduino

monitor_speed = 115200
upload_speed = 460800
monitor_rts = 0
monitor_dtr = 0

lib_deps =
    https://github.com/moononournation/Arduino_GFX.git#v1.5.6